// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttftczrvtgzjtafqvdci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0ZnRjenJ2dGd6anRhZnF2ZGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjc1NTAsImV4cCI6MjA3MDY0MzU1MH0.bkTtE-kBvGEHO2BNXKnGA3ULLeGhRbOlf97M5d7glX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});